CREATE DATABASE `fitnessData`;
USE `fitnessData`; 

CREATE TABLE Employee(
Eid VARCHAR(50) PRIMARY KEY,
Username VARCHAR(25),
Phone VARCHAR(30),
Email VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE `Member`(
  `Mid` VARCHAR(50) PRIMARY KEY,
  Firstname VARCHAR(50) NOT NULL,
  Lastname VARCHAR(50) NOT NULL,
  Birthday VARCHAR(30) NOT NULL,
  Phone VARCHAR(30) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Address VARCHAR(50) NOT NULL,
  Balance FLOAT DEFAULT 0
);

CREATE TABLE Product(
Pid VARCHAR(50) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
Price FLOAT DEFAULT 0
);


CREATE TABLE `Orders`(
oid INT PRIMARY KEY AUTO_INCREMENT,
Pid VARCHAR(50) NOT NULL,
`Mid` VARCHAR(50) NOT NULL,
createtime TIMESTAMP DEFAULT NOW() NOT NULL,
FOREIGN KEY (Pid) REFERENCES Product(Pid),
FOREIGN KEY (`Mid`) REFERENCES `Member`(`Mid`)
);

